# Generated by Django 3.1.1 on 2020-09-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BostRoast',
            new_name='BoastRoast',
        ),
    ]
