# Generated by Django 3.1.1 on 2020-10-01 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_api', '0002_auto_20200928_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroast',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='boastroast',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
